version: "3.7"
services: 
  db:
    image: postgis/postgis
    env_file: 
      - .env
    secrets:
      - db_password
  gui:
    build:
      context: gui/.
    restart: on-failure
    secrets:
      - db_password
  data-loader:
    build:
      context: data-loader/.
    env_file: 
      - .env
    restart: on-failure
    secrets:
      - db_password
  data-generator:
    build:
      context: data-generator/.
    env_file: 
      - .env
    restart: on-failure
    secrets:
      - db_password
secrets:
  db_password:
    file: ./db_password